# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Skunk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Skunk

end

target 'Skunk WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Skunk WatchKit App

end

target 'Skunk WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Skunk WatchKit Extension
  pod 'Kingfisher', '~> 6.0'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
end
